bind: "0.0.0.0:8080"
programs:
  nmsl:
    command: ./nmsl-telegram-bot
    env:
      TELOXIDE_TOKEN: $NMSL_TOKEN
      APP_BIND_ADDR: 127.0.0.1:8081
      APP_WEBHOOK_URL: https://aquarium.fly.dev/nmsl/
      APP_WEBHOOK_PATH: $NMSL_PATH
      APP_BIBLE: bible.json
      RUST_LOG: info
    http:
      port: 8081
      path: nmsl
      strip-path: true
      health-check:
        path: /health-check
        interval: 5s
        grace: 15s
  hithit:
    command: ./hithit_bot
    env:
      TELOXIDE_TOKEN: $HITHIT_TOKEN
      APP_BIND_ADDR: 127.0.0.1:8082
      APP_WEBHOOK_URL: https://aquarium.fly.dev/hithit/
      APP_WEBHOOK_PATH: $HITHIT_PATH
      RUST_LOG: info
    http:
      port: 8082
      path: hithit
      strip-path: true
      health-check:
        path: /health-check
        interval: 5s
        grace: 15s
  chi:
    command: ./chi-tg-inline-rs
    env:
      TELOXIDE_TOKEN: $CHI_TOKEN
      APP_BIND_ADDR: 127.0.0.1:8083
      APP_CORPUS_URL: https://raw.githubusercontent.com/Chi-Task-Force/Chi-Corpus/master/
      APP_WEBHOOK_URL: https://aquarium.fly.dev/chi/
      APP_WEBHOOK_PATH: $CHI_PATH
      RUST_LOG: info
    http:
      port: 8083
      path: chi
      strip-path: true
      health-check:
        path: /health-check
        interval: 5s
        grace: 15s
