on:
  repository_dispatch:
    types: [ deploy ]
  push:
    branches:
      - master

name: Deploy

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to fly.io
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch BLÅHAJ
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: deploy.yml
          workflow_conclusion: success
          branch: master
          name: release-musl
          path: .
          repo: PhotonQuantum/blahaj
      - name: Fetch nmsl
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: deploy.yml
          workflow_conclusion: success
          branch: master
          name: release-musl
          path: .
          repo: PhotonQuantum/nmsl-telegram-bot-rs
      - name: Fetch hithit
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: deploy.yml
          workflow_conclusion: success
          branch: master
          name: release-musl
          path: .
          repo: PhotonQuantum/hithit_bot
      - name: Fetch chi
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: deploy.yml
          workflow_conclusion: success
          branch: main
          name: release-musl
          path: .
          repo: Chi-Task-Force/Chi-Telegram-Inline-Bot-Neo
      - name: Launch
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"