on:
  repository_dispatch:
    types: [ deploy ]

name: Deploy

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to fly.io
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch BLÅHAJ
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: deploy.yml
          workflow_conclusion: success
          branch: master
          name: release-musl
          path: .
          repo: PhotonQuantum/blahaj
      - name: Fix Permissions
        run: chmod +x blahaj
      - name: Launch
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"